
CREATE DATABASE college;
CREATE DATABASE IF NOT EXISTS college;

DROP DATABASE ZomatoInventoryDB;

SHOW DATABASES;

USE college;

CREATE TABLE Student (
id INT PRIMARY KEY,
name VARCHAR(50),
age INT NOT NULL
);


SHOW TABLES;
DESCRIBE Student;

INSERT INTO Student VALUES (1,'ANKIT',21);
INSERT INTO Student VALUES (2,'AMAN',22);

INSERT INTO Student (id,name,age) VALUES (3,'PARUL',19),(4,'RONAK',20);

SELECT * FROM Student;
